import 'package:flutter/material.dart';

import 'responsive.dart';

/// Named spacing tokens; raw logical pixels remain explicitly separate.
enum FwSpace { s0, s1, s2, s3, s4, s5, s6, s8, s10, s12, s16, s24 }

@immutable
class FwSpacing {
  const FwSpacing({this.unit = 4}) : assert(unit >= 0);

  final double unit;

  double of(FwSpace token) =>
      const [0, 1, 2, 3, 4, 5, 6, 8, 10, 12, 16, 24][token.index] * unit;
}

enum FwRadius { none, sm, md, lg, xl, pill }

@immutable
class FwRadii {
  const FwRadii({this.sm = 4, this.md = 8, this.lg = 12, this.xl = 16});

  final double sm;
  final double md;
  final double lg;
  final double xl;

  double of(FwRadius radius) => switch (radius) {
    FwRadius.none => 0,
    FwRadius.sm => sm,
    FwRadius.md => md,
    FwRadius.lg => lg,
    FwRadius.xl => xl,
    FwRadius.pill => 999,
  };
}

enum FwColorRole {
  primary,
  onPrimary,
  surface,
  onSurface,
  outline,
  error,
  onError,
}

/// Semantic role pairs generated by Flutter's Material color algorithm.
@immutable
class FwColors {
  const FwColors(this.scheme);

  final ColorScheme scheme;

  Color of(FwColorRole role) => switch (role) {
    FwColorRole.primary => scheme.primary,
    FwColorRole.onPrimary => scheme.onPrimary,
    FwColorRole.surface => scheme.surface,
    FwColorRole.onSurface => scheme.onSurface,
    FwColorRole.outline => scheme.outline,
    FwColorRole.error => scheme.error,
    FwColorRole.onError => scheme.onError,
  };
}

/// Shared tokens. Structural breakpoint changes are discrete during animation.
class FwTheme extends ThemeExtension<FwTheme> {
  const FwTheme({
    required this.colors,
    required this.typography,
    this.spacing = const FwSpacing(),
    this.radii = const FwRadii(),
    this.breakpoints = FwBreakpoints.standard,
    this.minTapTarget = 48,
    this.focusWidth = 2,
  }) : assert(minTapTarget >= 48),
       assert(focusWidth > 0);

  factory FwTheme.light({Color seed = const Color(0xFF6750A4)}) =>
      FwTheme.fromSeed(seed: seed, brightness: Brightness.light);

  factory FwTheme.dark({Color seed = const Color(0xFF6750A4)}) =>
      FwTheme.fromSeed(seed: seed, brightness: Brightness.dark);

  factory FwTheme.fromSeed({
    required Color seed,
    required Brightness brightness,
  }) {
    final scheme = ColorScheme.fromSeed(
      seedColor: seed,
      brightness: brightness,
    );
    final typography = ThemeData(colorScheme: scheme).textTheme;
    return FwTheme(colors: FwColors(scheme), typography: typography);
  }

  final FwColors colors;
  final TextTheme typography;
  final FwSpacing spacing;
  final FwRadii radii;
  final FwBreakpoints breakpoints;
  final double minTapTarget;
  final double focusWidth;

  static FwTheme of(BuildContext context) {
    final theme = Theme.of(context).extension<FwTheme>();
    if (theme == null) {
      throw FlutterError(
        'FwTheme is missing. Use FwTheme.light().toThemeData() or register '
        'FwTheme in ThemeData.extensions.',
      );
    }
    return theme;
  }

  /// Maps framework roles into Material so native primitives share the theme.
  ThemeData toThemeData() => ThemeData(
    useMaterial3: true,
    colorScheme: colors.scheme,
    textTheme: typography,
    extensions: [this],
  );

  @override
  FwTheme copyWith({
    FwColors? colors,
    TextTheme? typography,
    FwSpacing? spacing,
    FwRadii? radii,
    FwBreakpoints? breakpoints,
    double? minTapTarget,
    double? focusWidth,
  }) => FwTheme(
    colors: colors ?? this.colors,
    typography: typography ?? this.typography,
    spacing: spacing ?? this.spacing,
    radii: radii ?? this.radii,
    breakpoints: breakpoints ?? this.breakpoints,
    minTapTarget: minTapTarget ?? this.minTapTarget,
    focusWidth: focusWidth ?? this.focusWidth,
  );

  @override
  FwTheme lerp(covariant FwTheme? other, double t) {
    if (other == null) return this;
    double mix(double a, double b) => a + (b - a) * t;
    return FwTheme(
      colors: FwColors(ColorScheme.lerp(colors.scheme, other.colors.scheme, t)),
      typography: TextTheme.lerp(typography, other.typography, t),
      spacing: FwSpacing(unit: mix(spacing.unit, other.spacing.unit)),
      radii: FwRadii(
        sm: mix(radii.sm, other.radii.sm),
        md: mix(radii.md, other.radii.md),
        lg: mix(radii.lg, other.radii.lg),
        xl: mix(radii.xl, other.radii.xl),
      ),
      breakpoints: t < 0.5 ? breakpoints : other.breakpoints,
      minTapTarget: mix(minTapTarget, other.minTapTarget),
      focusWidth: mix(focusWidth, other.focusWidth),
    );
  }
}

extension FwThemeContext on BuildContext {
  FwTheme get fwTheme => FwTheme.of(this);
}
